-- MySQL Script generated by MySQL Workbench
-- 12/04/16 20:32:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ceiba_negra
-- -----------------------------------------------------
-- Sistema para control de ventas de lotes
DROP SCHEMA IF EXISTS `ceiba_negra` ;

-- -----------------------------------------------------
-- Schema ceiba_negra
--
-- Sistema para control de ventas de lotes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ceiba_negra` DEFAULT CHARACTER SET utf8 ;
USE `ceiba_negra` ;

-- -----------------------------------------------------
-- Table `ceiba_negra`.`manzanas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceiba_negra`.`manzanas` ;

CREATE TABLE IF NOT EXISTS `ceiba_negra`.`manzanas` (
  `id_manzana` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `manzana` INT(4) UNSIGNED NOT NULL,
  `ref_calle` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_manzana`))
ENGINE = InnoDB
COMMENT = 'Estado de la manza, permitirá saber si se pueden vender lo cual permitira  diferenciar si se le pueden o no anexar lotes';


-- -----------------------------------------------------
-- Table `ceiba_negra`.`precios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceiba_negra`.`precios` ;

CREATE TABLE IF NOT EXISTS `ceiba_negra`.`precios` (
  `id_precio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `precio` DOUBLE UNSIGNED NOT NULL,
  `enganche` DOUBLE UNSIGNED NOT NULL,
  `pagos` DOUBLE UNSIGNED NOT NULL,
  PRIMARY KEY (`id_precio`))
ENGINE = InnoDB
COMMENT = 'Tabla de precios estandar por lote, servirá como recomendación pero se deberá de igual forma permitir alterar los precios en el contrato final por si se compra más de un lote o se llega a algún acuerdo en especifico.\n';


-- -----------------------------------------------------
-- Table `ceiba_negra`.`lotes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceiba_negra`.`lotes` ;

CREATE TABLE IF NOT EXISTS `ceiba_negra`.`lotes` (
  `id_lote` INT UNSIGNED NOT NULL,
  `id_manzana` INT(4) UNSIGNED NOT NULL,
  `lote` CHAR(4) NOT NULL,
  `superficie` DOUBLE(5,2) UNSIGNED NOT NULL,
  `id_precio` INT UNSIGNED NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `col_norte` VARCHAR(100) NOT NULL,
  `col_sur` VARCHAR(100) NOT NULL,
  `col_este` VARCHAR(100) NOT NULL,
  `col_oeste` VARCHAR(100) NOT NULL,
  `x` DOUBLE UNSIGNED NOT NULL COMMENT 'Cordenana x para el pluggin',
  `y` DOUBLE UNSIGNED NOT NULL COMMENT 'Coordenada y para el plugin',
  PRIMARY KEY (`id_lote`),
  INDEX `FK_Manzanas_Lotes_idx` (`id_manzana` ASC),
  INDEX `FK_Lotes_Precios_idx` (`id_precio` ASC),
  CONSTRAINT `FK_Lotes_Manzanas`
    FOREIGN KEY (`id_manzana`)
    REFERENCES `ceiba_negra`.`manzanas` (`id_manzana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Lotes_Precios`
    FOREIGN KEY (`id_precio`)
    REFERENCES `ceiba_negra`.`precios` (`id_precio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Fraccion de terreno a vender.\nLa superficie debe mostrarse en m^2, manejarlo con css\n';


-- -----------------------------------------------------
-- Table `ceiba_negra`.`lideres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceiba_negra`.`lideres` ;

CREATE TABLE IF NOT EXISTS `ceiba_negra`.`lideres` (
  `id_lider` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono` BIGINT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_lider`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceiba_negra`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceiba_negra`.`clientes` ;

CREATE TABLE IF NOT EXISTS `ceiba_negra`.`clientes` (
  `id_cliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceiba_negra`.`bancos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceiba_negra`.`bancos` ;

CREATE TABLE IF NOT EXISTS `ceiba_negra`.`bancos` (
  `id_banco` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cuenta` BIGINT UNSIGNED NOT NULL,
  `tarjeta` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_banco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceiba_negra`.`pantillas_contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceiba_negra`.`pantillas_contrato` ;

CREATE TABLE IF NOT EXISTS `ceiba_negra`.`pantillas_contrato` (
  `id_plantilla_contrato` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` INT UNSIGNED NOT NULL,
  `contrato_html` TEXT NOT NULL,
  PRIMARY KEY (`id_plantilla_contrato`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB
COMMENT = 'Datos repeditos\nFRANCISCO ENRIQUE MARTÍNEZ CORDERO  {$cedente}\nNombre del cliente en mayusculas 	              {$cesionario}\nManzana y lotes			              {$manzana}\nColindancia			              {$colindancias}';


-- -----------------------------------------------------
-- Table `ceiba_negra`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceiba_negra`.`ventas` ;

CREATE TABLE IF NOT EXISTS `ceiba_negra`.`ventas` (
  `id_venta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT UNSIGNED NOT NULL COMMENT 'Quien generó el contrato en el sistema',
  `id_cliente` INT UNSIGNED NOT NULL,
  `precio` DOUBLE UNSIGNED NOT NULL COMMENT 'Total del terreno ejemplo: $54,000.00',
  `enganche` DOUBLE UNSIGNED NOT NULL COMMENT 'Cuanto es el primer pago, ejemplo $4,000.00',
  `pagos` DOUBLE UNSIGNED NOT NULL COMMENT 'Cuanto se deberá pagar quincenal o mensualmente por el terreno ejemplo : $3,000',
  `n_pagos` INT UNSIGNED NOT NULL COMMENT 'Cantidad de pagos que se deberán hacer para saldar el precio del terreno:\nSuponiendo que el precio es de : $54,000.00\n                           el enganche de:   $4,000.00\nY los pagos de $3,000.00\nTenemos n_pagos = (precio - enganche) / pagos',
  `plazo` ENUM('quincenal', 'mensual') NOT NULL COMMENT 'Como se realizarán los pagos, quincenales o mensaules',
  `contrato` TEXT NOT NULL COMMENT 'Interpolará las variables de la plantilla del contrato y lo guardará para reportear.\n',
  `fecha_contrato` DATE NOT NULL,
  `insert_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_venta`),
  INDEX `FK_Ventas_Clientes_idx` (`id_cliente` ASC),
  CONSTRAINT `FK_Ventas_Clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `ceiba_negra`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Se guarda lo real';


-- -----------------------------------------------------
-- Table `ceiba_negra`.`lotes_venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceiba_negra`.`lotes_venta` ;

CREATE TABLE IF NOT EXISTS `ceiba_negra`.`lotes_venta` (
  `id_lote_venta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_lote` INT UNSIGNED NOT NULL,
  `id_venta` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_lote_venta`),
  INDEX `FK_Lotes_venta_Lotes_idx` (`id_lote` ASC),
  INDEX `FK_Lotes_ventas_Ventas_idx` (`id_venta` ASC),
  CONSTRAINT `FK_Lotes_venta_Lotes`
    FOREIGN KEY (`id_lote`)
    REFERENCES `ceiba_negra`.`lotes` (`id_lote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Lotes_ventas_Ventas`
    FOREIGN KEY (`id_venta`)
    REFERENCES `ceiba_negra`.`ventas` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceiba_negra`.`terreno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceiba_negra`.`terreno` ;

CREATE TABLE IF NOT EXISTS `ceiba_negra`.`terreno` (
  `id_terreno` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `nombre_propietario` VARCHAR(45) NOT NULL,
  `apellidos_propietario` VARCHAR(45) NOT NULL,
  `col_norte` VARCHAR(45) NOT NULL,
  `col_sur` VARCHAR(45) NOT NULL,
  `col_este` VARCHAR(45) NOT NULL,
  `col_oeste` VARCHAR(45) NOT NULL,
  `hectaria` VARCHAR(45) NOT NULL,
  `area` VARCHAR(45) NOT NULL,
  `centiarea` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_terreno`))
ENGINE = InnoDB
COMMENT = 'Puntos cardinales\nNorte, Sur, Este, Oeste\nNoreste,Noroeste,Sureste y Suroeste';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ceiba_negra`.`manzanas`
-- -----------------------------------------------------
START TRANSACTION;
USE `ceiba_negra`;
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (1, 1, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (2, 2, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (3, 3, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (4, 4, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (5, 5, 'Palma de coco', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (6, 6, 'Palma real', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (7, 7, 'Palma plumosa', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (8, 8, 'Palma de chiit', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (9, 9, 'Palma de guano', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (10, 10, 'Palma corozo', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (11, 11, 'Akits', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (12, 12, 'Balch�', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (13, 13, 'Chacah', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (14, 14, 'Bamb�', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (15, 15, 'Palmera formosa', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (16, 16, 'Palmera azul', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (17, 17, 'Tagua', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (18, 18, 'Quitasol', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (19, 19, 'Palmera azucarera', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (20, 20, 'Sendero la ceiba', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (21, 21, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (22, 22, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (23, 23, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (24, 24, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (25, 25, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (26, 26, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (27, 27, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (28, 28, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (29, 29, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (30, 30, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (31, 31, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (32, 32, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (33, 33, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (34, 34, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (35, 35, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (36, 36, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (37, 37, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (38, 38, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (39, 39, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (40, 40, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (41, 41, '', 1);
INSERT INTO `ceiba_negra`.`manzanas` (`id_manzana`, `manzana`, `ref_calle`, `estado`) VALUES (42, 42, '', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ceiba_negra`.`precios`
-- -----------------------------------------------------
START TRANSACTION;
USE `ceiba_negra`;
INSERT INTO `ceiba_negra`.`precios` (`id_precio`, `precio`, `enganche`, `pagos`) VALUES (1, 45000, 0, 0);
INSERT INTO `ceiba_negra`.`precios` (`id_precio`, `precio`, `enganche`, `pagos`) VALUES (2, 77000, 0, 0);
INSERT INTO `ceiba_negra`.`precios` (`id_precio`, `precio`, `enganche`, `pagos`) VALUES (3, 99000, 0, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ceiba_negra`.`lotes`
-- -----------------------------------------------------
START TRANSACTION;
USE `ceiba_negra`;
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (1, 5, '1A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (2, 5, '1B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (3, 5, '2A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (4, 5, '2B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (5, 5, '3A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (6, 5, '3B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (7, 5, '4A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (8, 5, '4B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (9, 5, '5A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (10, 5, '5B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (11, 5, '6A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (12, 5, '6B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (13, 5, '7A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (14, 5, '7B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (15, 5, '8A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (16, 5, '8B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (17, 5, '9A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (18, 5, '9B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (19, 5, '10A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (20, 5, '10B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (21, 6, '1A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (22, 6, '1B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (23, 6, '2A', 312.5, 1, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (24, 6, '2B', 312.5, 1, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (25, 6, '3A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (26, 6, '3B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (27, 6, '4A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (28, 6, '4B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (29, 6, '5A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (30, 6, '5B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (31, 6, '6A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (32, 6, '6B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (33, 6, '7A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (34, 6, '7B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (35, 6, '8A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (36, 6, '8B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (37, 6, '9A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (38, 6, '9B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (39, 6, '10A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (40, 6, '10B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (41, 7, '1A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (42, 7, '1B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (43, 7, '2A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (44, 7, '2B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (45, 7, '3A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (46, 7, '3B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (47, 7, '4A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (48, 7, '4B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (49, 7, '5A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (50, 7, '5B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (51, 7, '6A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (52, 7, '6B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (53, 7, '7A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (54, 7, '7B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (55, 7, '8A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (56, 7, '8B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (57, 7, '9A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (58, 7, '9B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (59, 7, '10A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (60, 7, '10B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (61, 8, '1A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (62, 8, '1B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (63, 8, '2A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (64, 8, '2B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (65, 8, '3A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (66, 8, '3B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (67, 8, '4A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (68, 8, '4B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (69, 8, '5A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (70, 8, '5B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (71, 8, '6A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (72, 8, '6B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (73, 8, '7A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (74, 8, '7B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (75, 8, '8A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (76, 8, '8B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (77, 8, '9A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (78, 8, '9B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (79, 8, '10A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (80, 8, '10B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (81, 9, '1A', 312.5, 1, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (82, 9, '1B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (83, 9, '2A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (84, 9, '2B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (85, 9, '3A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (86, 9, '3B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (87, 9, '4A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (88, 9, '4B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (89, 9, '5A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (90, 9, '5B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (91, 9, '6A', 312.5, 1, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (92, 9, '6B', 312.5, 1, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (93, 9, '7A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (94, 9, '7B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (95, 9, '8A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (96, 9, '8B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (97, 9, '9A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (98, 9, '9B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (99, 9, '10A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (100, 9, '10B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (101, 10, '1A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (102, 10, '1B', 312.5, 1, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (103, 10, '2A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (104, 10, '2B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (105, 10, '3A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (106, 10, '3B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (107, 10, '4A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (108, 10, '4B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (109, 10, '5A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (110, 10, '5B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (111, 10, '6A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (112, 10, '6B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (113, 10, '7A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (114, 10, '7B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (115, 10, '8A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (116, 10, '8B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (117, 10, '9A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (118, 10, '9B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (119, 10, '10A', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (120, 10, '10B', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (121, 11, '1', 312.5, 2, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (122, 11, '2', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (123, 11, '3', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (124, 11, '4', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (125, 11, '5', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (126, 11, '6', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (127, 11, '7', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (128, 11, '8', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (129, 11, '9', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (130, 11, '10', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (131, 11, '11', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (132, 11, '12', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (133, 11, '13', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (134, 11, '14', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (135, 11, '15', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (136, 11, '16', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (137, 11, '17', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (138, 11, '18', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (139, 11, '19', 312.5, 2, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (140, 11, '20', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (141, 12, '1', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (142, 12, '2', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (143, 12, '3', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (144, 12, '4', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (145, 12, '5', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (146, 12, '6', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (147, 12, '7', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (148, 12, '8', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (149, 12, '9', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (150, 12, '10', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (151, 12, '11', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (152, 12, '12', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (153, 12, '13', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (154, 12, '14', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (155, 12, '15', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (156, 12, '16', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (157, 12, '17', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (158, 12, '18', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (159, 12, '19', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (160, 12, '20', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (161, 13, '1', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (162, 13, '2', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (163, 13, '3', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (164, 13, '4', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (165, 13, '5', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (166, 13, '6', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (167, 13, '7', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (168, 13, '8', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (169, 13, '9', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (170, 13, '10', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (171, 13, '11', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (172, 13, '12', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (173, 13, '13', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (174, 13, '14', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (175, 13, '15', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (176, 13, '16', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (177, 13, '17', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (178, 13, '18', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (179, 13, '19', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (180, 13, '20', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (181, 14, '1', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (182, 14, '2', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (183, 14, '3', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (184, 14, '4', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (185, 14, '5', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (186, 14, '6', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (187, 14, '7', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (188, 14, '8', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (189, 14, '9', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (190, 14, '10', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (191, 14, '11', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (192, 14, '12', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (193, 14, '13', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (194, 14, '14', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (195, 14, '15', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (196, 14, '16', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (197, 14, '17', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (198, 14, '18', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (199, 14, '19', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (200, 14, '20', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (201, 15, '1', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (202, 15, '2', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (203, 15, '3', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (204, 15, '4', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (205, 15, '5', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (206, 15, '6', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (207, 15, '7', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (208, 15, '8', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (209, 15, '9', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (210, 15, '10', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (211, 15, '11', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (212, 15, '12', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (213, 15, '13', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (214, 15, '14', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (215, 15, '15', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (216, 15, '16', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (217, 15, '17', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (218, 15, '18', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (219, 15, '19', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (220, 15, '20', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (221, 16, '1', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (222, 16, '2', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (223, 16, '3', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (224, 16, '4', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (225, 16, '5', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (226, 16, '6', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (227, 16, '7', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (228, 16, '8', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (229, 16, '9', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (230, 16, '10', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (231, 16, '11', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (232, 16, '12', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (233, 16, '13', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (234, 16, '14', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (235, 16, '15', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (236, 16, '16', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (237, 16, '17', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (238, 16, '18', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (239, 16, '19', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (240, 16, '20', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (241, 17, '1', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (242, 17, '2', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (243, 17, '3', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (244, 17, '4', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (245, 17, '5', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (246, 17, '6', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (247, 17, '7', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (248, 17, '8', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (249, 17, '9', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (250, 17, '10', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (251, 17, '11', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (252, 17, '12', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (253, 17, '13', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (254, 17, '14', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (255, 17, '15', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (256, 17, '16', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (257, 17, '17', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (258, 17, '18', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (259, 17, '19', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (260, 17, '20', 312.5, 3, 1, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (261, 18, '1', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (262, 18, '2', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (263, 18, '3', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (264, 18, '4', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (265, 18, '5', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (266, 18, '6', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (267, 18, '7', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (268, 18, '8', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (269, 18, '9', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (270, 18, '10', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (271, 18, '11', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (272, 18, '12', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (273, 18, '13', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (274, 18, '14', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (275, 18, '15', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (276, 18, '16', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (277, 18, '17', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (278, 18, '18', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (279, 18, '19', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (280, 18, '20', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (281, 19, '1', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (282, 19, '2', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (283, 19, '3', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (284, 19, '4', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (285, 19, '5', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (286, 19, '6', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (287, 19, '7', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (288, 19, '8', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (289, 19, '9', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (290, 19, '10', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (291, 19, '11', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (292, 19, '12', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (293, 19, '13', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (294, 19, '18', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (295, 19, '19', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (296, 19, '20', 312.5, 1, 0, '', '', '', '', DEFAULT, DEFAULT);
INSERT INTO `ceiba_negra`.`lotes` (`id_lote`, `id_manzana`, `lote`, `superficie`, `id_precio`, `estado`, `col_norte`, `col_sur`, `col_este`, `col_oeste`, `x`, `y`) VALUES (297, 20, '1', 0, 1, 0, '', '', '', '', DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ceiba_negra`.`lideres`
-- -----------------------------------------------------
START TRANSACTION;
USE `ceiba_negra`;
INSERT INTO `ceiba_negra`.`lideres` (`id_lider`, `nombre`, `apellidos`, `correo`, `telefono`) VALUES (1, 'Samuel', 'Rojas Too', 'samuel_-_rojas@hotmail.com', 9982121131);

COMMIT;

