-- MySQL Script generated by MySQL Workbench
-- 11/29/16 23:42:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ceiba_negra
-- -----------------------------------------------------
-- Sistema para control de ventas de lotes
DROP SCHEMA IF EXISTS `ceiba_negra` ;

-- -----------------------------------------------------
-- Schema ceiba_negra
--
-- Sistema para control de ventas de lotes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ceiba_negra` DEFAULT CHARACTER SET utf8 ;
USE `ceiba_negra` ;

-- -----------------------------------------------------
-- Table `ceiba_negra`.`manzanas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceiba_negra`.`manzanas` ;

CREATE TABLE IF NOT EXISTS `ceiba_negra`.`manzanas` (
  `id_manzana` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `manzana` INT(4) UNSIGNED NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_manzana`))
ENGINE = InnoDB
COMMENT = 'Estado de la manza, permitirá saber si se pueden vender lo cual permitira  diferenciar si se le pueden o no anexar lotes';


-- -----------------------------------------------------
-- Table `ceiba_negra`.`lotes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceiba_negra`.`lotes` ;

CREATE TABLE IF NOT EXISTS `ceiba_negra`.`lotes` (
  `id_lote` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_manzana` INT(4) UNSIGNED NOT NULL,
  `lote` CHAR(4) NOT NULL,
  `superficie` DOUBLE NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_lote`, `id_manzana`),
  INDEX `FK_Manzanas_Lotes_idx` (`id_manzana` ASC),
  CONSTRAINT `FK_Lotes_Manzanas`
    FOREIGN KEY (`id_manzana`)
    REFERENCES `ceiba_negra`.`manzanas` (`id_manzana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Fraccion de terreno a vender.\nLa superficie debe mostrarse en m^2, manejarlo con css\n';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
